#!/usr/bin/env sh

sudo_path="/usr/bin/sudo"
alias sudo="sudoer_lecture.sh && \$sudo_path"

alias ls='lsd'
alias du='dust'
alias df='duf'

alias mkvenv="mkvenv --system-site-packages"

alias ip="ip -c"
alias l="ls -lAht"
alias r="ranger"
alias vim="nvim"

alias techdocs="podman run -it --rm --network host -v \$PWD:/app techdocs:latest techdocs serve"
alias gibip="curl --fail-with-body https://icanhazip.com"
