#!/usr/bin/env sh

alias ls='lsd'
alias du='dust'
alias df='duf'

alias mkvenv="mkvenv --system-site-packages"

alias ip="ip -c"
alias l="ls -lAht"
alias r="ranger"
alias vim="nvim"

alias gibip="curl --fail-with-body https://icanhazip.com"
