#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 32 -xoffset -10 -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Noto Mono 10" <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) lockscreen ;;
                *Logout) qdbus org.kde.ksmserver /KSMServer logout 0 0 0;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
