#!/bin/sh

udiskie &

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

# Set monitors
~/.screenlayout/desktop.sh

# Set background
feh --bg-fill ~/.config/wall.png &

# Set caps lock as escape
setxkbmap -layout us -variant altgr-intl -option nodeadkeys -option 'caps:escape' &

# Notifications
dunst &

# Polkit authentication manager
/usr/lib/polkit-kde-authentication-agent-1 &

# mpd startup
mopidy &

# Composite manager:
picom --daemon &

# Location agent
/usr/lib/geoclue-2.0/demos/agent &

# Redshift for warmer light in the evening
redshift-gtk &

# Autohide cursor
unclutter -b &

caffeine -a &

playerctld daemon &

# clipboard manager
clipcatd &

# Window manager
exec i3
