bg0 = "%light2"
bg1 = "%light1"
bg2 = "%light2"
bg3 = "%light3"
bg4 = "%light4"
fg0 = "%dark0"
fg1 = "%dark1"
fg2 = "%dark2"
fg3 = "%dark3"
fg4 = "%dark4"
red = "%faded_red"
green = "%faded_green"
yellow = "%faded_yellow"
blue = "%faded_blue"
purple = "%faded_purple"
aqua = "%faded_aqua"
orange = "%faded_orange"
