##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Windows

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class  .*

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_initial_focus on

# Firefox
windowrule = workspace 2, match:class ^(firefox)$

# Thunderbird
windowrule = workspace 3, match:class ^(org.mozilla.Thunderbird)$

# Bitwarden Chrome Extension
windowrule = tag +floating-window, match:class ^(chrome-nngceckbapebfimnlniiiahkandclblb-Default)$

# Steam
# Steam updater
windowrule = float on, center on, match:class ^()$, match:title Steam
# Steam
windowrule = workspace 9, match:class ^(steam)$
windowrule = center on, match:class ^(steam)$, match:title Steam
windowrule = opacity 1 1, match:class steam
windowrule = float on, match:class ^(steam)$, match:title Friends List
windowrule = idle_inhibit fullscreen, match:class steam
# Steam games
windowrule = workspace 9, match:class ^(steam_app_.*)$

# Floating windows
windowrule = float on, match:tag floating-window
windowrule = center on, match:tag floating-window
windowrule = size 875 600, match:tag floating-window

windowrule = tag +floating-window, match:class (blueberry.py|com.omarchy.Impala|com.omarchy.Wiremix|com.omarchy.Omarchy|org.gnome.NautilusPreviewer|com.gabm.satty|Omarchy|About|TUI.float|^chrome-[a-z]+-Default$)
windowrule = tag +floating-window, match:class (xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus), match:title ^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)
windowrule = float on, match:class org.gnome.Calculator
windowrule = tag +floating-window, match:class ^(org.mozilla.Thunderbird)$, match:title ^(.* Reminders)$
windowrule = tag +floating-window, match:class ^(org.mozilla.Thunderbird)$, match:title ^(Message Filters)$
# All other Thunderbird windows, e.g., event editor
windowrule = tag +floating-window, match:class ^(org.mozilla.Thunderbird)$, match:title ^()$
# Empty
windowrule = tag +floating-window, match:class ^()$, match:title ^()$
# Nextcloud
windowrule = tag +floating-window, match:class $(com.nextcloud.desktopclient.nextcloud)$, match:title ^(Nextcloud)$

# Workspaces

{{hyprland_workspace_rules}}
