#!/bin/bash

month=$(date +%m)
year=$(date +%Y)
unipath="$1"

semester=""

if [ "$month" -ge 10 ]
then
    nextyear=$(( "$year" + 1 ))
    semester="Wintersemester$year-$nextyear"
elif [ "$month" -gt 3 ] && [ "$month" -lt 10 ]
then
    semester="Sommersemester$year"
else
    prevyear=$(( "$year" - 1 ))
    semester="Wintersemester$prevyear-$year"
fi

echo "$unipath/$semester"

