#!/bin/bash

get_image_name ()
{
    image_type="$1"
    echo "screenshot_${image_type}_$(date --iso-8601=seconds).png"
}

output_folder="${HOME}/Pictures/screenshots"
selection="$(rofi -sep '|' -dmenu -p "Screenshot which area?" <<< "current window (copy)|a selected area (copy)|full screen (copy)|current window|a selected area|full screen")"

# Wait for rofi window to disappear
sleep 0.2

case "$selection" in
    "current window") image_name="$(get_image_name current_window)"; hyprshot --freeze -m window -m active --filename "$image_name" --output-folder "$output_folder" ;;
    "a selected area") image_name="$(get_image_name selected_area)"; hyprshot --freeze -m region --filename "$image_name" --output-folder "$output_folder" ;;
    "full screen") image_name="$(get_image_name full_screen)"; hyprshot --freeze -m output -m active --filename "$image_name" --output-folder "$output_folder" ;;
    "current window (copy)") hyprshot --freeze -m window -m active --clipboard-only ;;
    "a selected area (copy)") hyprshot --freeze -m region --clipboard-only ;;
    "full screen (copy)") hyprshot --freeze -m output -m active --clipboard-only ;;
esac
