#!/bin/sh
# Codi
# Usage: codi [filetype] [filename]
syntax="${1:-python}"
filename="";

if [ $# -ge 1 ]; then
    shift
    filename="$1"
fi
if [ -z "$filename" ]; then
    filename="/tmp/$RANDOM.py"
fi
nvim -c "Codi $syntax" -c "startinsert" "$filename"

