#!/bin/sh

for file in $1/*.mp3 ; do
    artist=$(echo $file | awk -F ' - ' '{print $1}' | awk -F '/' '{print $2}')
    title=$(echo $file | awk -F ' - ' '{print $2}' | awk -F '-' '{print $1}')
    mp3info -a "$artist" -t "$title" "$file"
done
