#!/bin/sh
# Sets the background. If given an argument, will set file as background.
[ ! -z "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Wallpaper changed."

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI1')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xwallpaper --output eDP1 --zoom ~/.config/wall.png --output HDMI1 --zoom ~/.config/wall.png
else
    xwallpaper --output "HDMI-2" --zoom ~/.config/wall.png
fi

