#!/bin/sh

message="Do not disturb mode is now "
if [ "$(xfconf-query -c xfce4-notifyd -p /do-not-disturb)" = "false" ]
then
    notif-send "$message on"
    xfconf-query -c xfce4-notifyd -p /do-not-disturb -T
else
    xfconf-query -c xfce4-notifyd -p /do-not-disturb -T
    notif-send "$message off"
fi
