#!/bin/bash
# 'rx' or 'tx'
TYPE=$1
if [ "$1" != "rx" -a "$1" != "tx" ]; then
    echo "Invalid argument: $1" 1>&2
    echo "Must be 'tx' or 'rx'" 1>&2
    echo "Usage: $0 (rx|tx)" 1>&2
    exit 1
fi
NETDIR="/sys/class/net"
function total_bytes() {
    local bytecount=0
    for IFACE in $(ls -1 $NETDIR -Ilo); do
        # sum ${TYPE}_bytes for all network interfaces
        F="$NETDIR/$IFACE/statistics/${TYPE}_bytes"
        let bytecount+=$(<$F)
    done
    echo $bytecount
}
BEFORE=$(total_bytes)
sleep 1

if [[ $BEFORE -eq $(total_bytes) ]]; then
    color="#505050"
fi
if [[ "$TYPE" == "rx" ]]; then
	symbol="⬇"
else
	symbol="⬆"
fi
echo "$symbol"
echo "$symbol"
echo $color
exit 0
