#!/bin/bash

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 32 -xoffset -10 -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Noto Mono 10" <<< " Lock| Logout|⏾ Suspend|❆ Hibernate| Reboot| Shutdown")"

case "$MENU" in
   *Lock)        betterlockscreen -l            ;;
   *Logout)      i3-msg             exit        ;;
   *Suspend)     systemctl          suspend     ;;
   *Hibernate)   systemctl          hibernate   ;;
   *Reboot)      systemctl          reboot      ;;
   *Shutdown)    systemctl       -i poweroff
esac
