!/bin/sh

udiskie &

setxkbmap -layout us -variant altgr-intl -option nodeadkeys -option 'caps:escape'

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

# Set monitors
~/.screenlayout/desktop.sh

# Set background
feh --bg-fill ~/.config/wall.png &

# Set caps lock as escape
setxkbmap -option 'caps:escape' &

# Notifications
/usr/lib/xfce4/notifyd/xfce4-notifyd &

# Polkit authentication manager
/usr/lib/polkit-kde-authentication-agent-1 &

# mpd startup
mopidy &

# Composite manager:
picom -b &

# Redshift for warmer light in the evening
redshift-gtk -l 52.53878:13.42443 &

# Autohide cursor
unclutter -b &

caffeine -a &

playerctld daemon &

# Window manager
exec i3
