#!/bin/sh

udiskie &

setxkbmap -layout us -variant altgr-intl -option nodeadkeys -option 'caps:escape'

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

# Set monitors
~/.screenlayout/desktop.sh

# Set background
feh --bg-fill ~/.config/wall.png &

# Set caps lock as escape
setxkbmap -option 'caps:escape' &

# Notifications
dunst &

# Polkit authentication manager
/usr/lib/polkit-kde-authentication-agent-1 &

# mpd startup
mopidy &

# Composite manager:
picom -b &

# Location agent
/usr/lib/geoclue-2.0/demos/agent &

# Redshift for warmer light in the evening
redshift-gtk &

# Autohide cursor
unclutter -b &

caffeine -a &

playerctld daemon &

# Clipboard manager
clipcatd &
clipcatctl enable-monitor &

# Window manager
exec i3
