#!/bin/bash

image_name="$HOME/Pictures/screenshots/$(date '+%d-%m-%y_%H-%M-%S').png"

selection="$(rofi -sep '|' -dmenu -p "Screenshot which area?" <<< "current window|a selected area|full screen|current window (copy)|a selected area (copy)|full screen (copy)")"

case "$selection" in
    "current window") maim -i "$(xdotool getactivewindow)" $image_name && notify-send "Screenshot '$image_name' taken." ;;
    "a selected area") maim -s "$image_name" && notify-send "Screenshot '$image_name' taken." ;;
    "full screen") maim "$image_name" && notify-send "Screenshot '$image_name' taken." ;;
    "current window (copy)") maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
    "a selected area (copy)") maim -s | xclip -selection clipboard -t image/png ;;
    "full screen (copy)") maim | xclip -selection clipboard -t image/png ;;
esac
