#!/bin/sh
# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

[ "$(printf "No\\nYes" | dmenu -i -p "$1" -nb \#0d6251 -sb \#5b2c70 -sf \#93e0e3 -nf \#dfaf8f )" = "Yes" ] && $2
