#!/bin/zsh

SESSIONNAME="Mochi"

create_mochi(){
    tmux new-session -d -s $SESSIONNAME >/dev/null
    tmux rename-window -t $SESSIONNAME:0 'dotfiles'
    tmux send-keys -t $SESSIONNAME 'cd ~/.config' Enter
    tmux send-keys -t $SESSIONNAME 'nvim nvim/init.vim' Enter
    tmux splitw -v -p 30 -t $SESSIONNAME:0.0
    tmux splitw -h -t $SESSIONNAME:0.1
    tmux send-keys -t $SESSIONNAME:0.1 'cd ~/.dotfiles' Enter
    tmux send-keys -t $SESSIONNAME:0.1 'git log --graph --decorate --all --stat' Enter
    tmux send-keys -t $SESSIONNAME:0.2 'cd ~/.dotfiles' Enter

    tmux new-window -t $SESSIONNAME
    tmux rename-window -t $SESSIONNAME:1 'gotop'
    tmux send-keys -t $SESSIONNAME:1.0 'gotop' Enter

    tmux new-window -t $SESSIONNAME
    tmux rename-window -t $SESSIONNAME:2 'ncmpcpp'
    tmux send-keys -t $SESSIONNAME:2 'ncmpcpp' Enter

    tmux new-window -t $SESSIONNAME
    tmux rename-window -t $SESSIONNAME:3 'projects'
    tmux send-keys -t $SESSIONNAME:3.0 "cd ~/Projects" Enter
    tmux send-keys -t $SESSIONNAME:3.0 "ranger" Enter

    tmux new-window -t $SESSIONNAME

}

tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]; then
    create_mochi
fi

tmux attach -t $SESSIONNAME
