#!/bin/bash

SESSIONNAME="Mochi"

create_mochi(){
    tmux new-session -d -s $SESSIONNAME >/dev/null
    tmux rename-window -t $SESSIONNAME:0 'dotfiles'
    tmux send-keys -t $SESSIONNAME 'pushd ~/.dotfiles' Enter
    tmux send-keys -t $SESSIONNAME 'nvim .config/nvim/init.vim' Enter

    tmux new-window -t $SESSIONNAME
    tmux rename-window -t $SESSIONNAME:1 'bashtop'
    tmux send-keys -t $SESSIONNAME:1.0 'bashtop' Enter

    tmux new-window -t $SESSIONNAME
    tmux rename-window -t $SESSIONNAME:2 'ncmpcpp'
    tmux send-keys -t $SESSIONNAME:2 'ncmpcpp' Enter

    tmux new-window -t $SESSIONNAME

}

if ! tmux has-session -t $SESSIONNAME &> /dev/null
then
    create_mochi
fi

[ "$1" != "-d" ] && tmux attach -t $SESSIONNAME || true
